[package]
name = "pico-enviro-sensor"
description = "Firmware for RPi Pico 2 W-based environment sensor"
authors = ["Adam Macdonald"]
homepage = "https://github.com/twokilohertz/pico-enviro-sensor"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
fugit = "0.3.7"
panic-halt = "1.0.0"
rp235x-hal = { version = "0.2.0", features = [
    "critical-section-impl",
    "binary-info",
] }

# Super-optimised release build, maximum performance, minimal debuggability
# Build with cargo build --profile dist
[profile.dist]
inherits = "release"
opt-level = 3
strip = "symbols"
lto = "fat"
overflow-checks = false
codegen-units = 1
