[package]
name = "pico-enviro-sensor"
version = "0.2.0"
description = "Firmware for RP235x-based environment sensing device"
authors = ["Adam Macdonald <adam@2khz.xyz>"]
repository = "https://git.2khz.xyz/adam/pico-enviro-sensor"
readme = "README.md"
license = "MIT"
rust-version = "1.95"
edition = "2024"
publish = false

[dependencies]
# Hardware
cortex-m = { version = "0.7", features = ["critical-section"] }
cortex-m-rt = { version = "0.7" }
# Embassy
embassy-rp = { version = "0.10", features = [
    "rp235xa",
    "binary-info",
    "imagedef-none",
    "critical-section-impl",
    "time-driver",
] }
embassy-executor = { version = "0.10", features = [
    "platform-cortex-m",
    "executor-thread",
    "executor-interrupt",
] }
embassy-futures = { version = "0.1" }
embassy-sync = { version = "0.8" }
embassy-time = { version = "0.5" }
embassy-embedded-hal = { version = "0.6" }
# Graphics
embedded-graphics = { version = "0.8" }
embedded-graphics-framebuf = { version = "0.5" }
# Drivers
scd4x = { git = "https://github.com/twokilohertz/scd4x-rs.git", branch = "develop", features = [
    "scd41",
    "fixed",
] } # Sensor
mipidsi = { version = "0.10" } # Display
# Containers
heapless = { version = "0.9", default-features = false }
circular-buffer = { version = "2.0", default-features = false }
# Utilities
static_cell = { version = "2.1", default-features = false }
fixed = { version = "1" }
tinybmp = { version = "0.7" }
# Debugging
rtt-target = { version = "0.6" }

[profile.dev]
opt-level = "s"
strip = "none"

[profile.dist]
inherits = "release"
opt-level = 3
strip = "symbols"
lto = "fat"
panic = "abort"
overflow-checks = false
codegen-units = 1

[profile.dist-dev]
inherits = "dist"
strip = "none"
